definitions:
  controller.dataCreateProductPost:
    properties:
      name:
        type: string
      price:
        type: number
    type: object
  controller.dataGetAllProductsReturn:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Product'
        type: array
    type: object
  controller.dataGetProductByIdReturn:
    properties:
      data:
        $ref: '#/definitions/model.Product'
    type: object
  model.Product:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/products:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.dataGetAllProductsReturn'
      summary: récupère tous les produits de la base de données et les renvoie en
        format JSON
      tags:
      - Product
  /api/products/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Product object
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/controller.dataCreateProductPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.dataGetProductByIdReturn'
      summary: crée un nouveau produit dans la base de données et le renvoie en format
        JSON
      tags:
      - Product
  /api/products/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.dataGetProductByIdReturn'
      summary: récupère le produit de la base de données avec son id et les renvoie
        en format JSON
      tags:
      - Product
swagger: "2.0"
